language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  exclude:
    - php: hhvm
      env: PHP_BIN=php-cgi
  include:
    - php: 7.0
      env: PHP_BIN=phpdbg COVERAGE="--coverage ./coverage.xml --coverage-src ./app"
install:
  # Update Composer
  - composer self-update
  - composer install --dev
  # Install Nette Tester
  - composer update --no-interaction
  # Install Nette Code checker
  - composer create-project nette/code-checker temp/code-checker --no-interaction
script:
  # Nette Tester
  - vendor/bin/tester -p $PHP_BIN -s $COVERAGE ./tests
  # Nette Code checker
  - php temp/code-checker/src/code-checker.php -l --short-arrays
after_success:
  - 'if [ "$COVERAGE" != "" ]; then bash <(curl -s https://codecov.io/bash); fi;'
after_failure:
   Print *.actual content
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
