language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi
matrix:
  include:
    - php: 7.0
      env: PHP_BIN=phpdbg CODE_CHECKER=true
    - php: 7.0
      env: PHP_BIN=phpdbg COVERAGE="--coverage ./coverage.xml --coverage-src ./app"
install:
  # Update Composer
  - composer self-update
  - composer install
  # Install Nette Tester
  - composer update --no-interaction
  # Install Nette Code checker
  - 'if [[ "$CODE_CHECKER" = true ]]; then composer create-project nette/code-checker temp/code-checker --no-interaction; fi;'
script:
  # Nette Code checker
  - 'if [[ "$CODE_CHECKER" = true ]]; then php temp/code-checker/src/code-checker.php -l --short-arrays; fi;'
  # Nette Tester
  - vendor/bin/tester -p $PHP_BIN -s $COVERAGE ./tests
after_success:
  # Nette Code checker
  - 'if [[ "$COVERAGE" != "" ]]; then bash <(curl -s https://codecov.io/bash); fi;'
after_failure:
  # Print *.actual content
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
