language: php
php:
  - 5.6
  - 7.0
  - 7.1
env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi
install:
  # Update Composer
  - travis_retry composer self-update
  - travis_retry composer install
  # Install Nette Tester
  - travis_retry composer update --no-interaction
script:
  # Nette Tester
  - vendor/bin/tester -p $PHP_BIN -s ./tests
after_failure:
  # Print *.actual content
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
jobs:
  include:
    - stage: Code Standard Checker
      php: 7.1
      install:
        # Install Nette Code Checker
        - travis_retry composer create-project nette/code-checker temp/code-checker --no-interaction
      script:
        - php temp/code-checker/src/code-checker.php -l --short-arrays -i "tests/model/data/macros-ascii.expected"
    - stage: Code Coverage
      php: 7.1
      script:
        - vendor/bin/tester -p phpdbg -s --coverage ./coverage.xml --coverage-src ./app ./tests
      after_script:
        - bash <(curl -s https://codecov.io/bash)
  allow_failures:
    - stage: Code Coverage
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
